### ISSUE TITLE
Consider explaining the term "assign"

### ISSUE THREAD

**Issue by JimmyStevens** [RVAGameJams/learn2love#1]
When I started I kept getting hung up on how the '=' sign was no longer 'equal' but became an assigned value. 

https://github.com/RVAGameJams/learn2love/blob/567ea6021342650ea296c90b81d0fcc4b42e5502/docs/pages/01-03-nil-and-variables.html#L576

**Comment by jaythomas** [comment]
From my experience explaining it to others, most people that see the `=` sign will think about how it works in Algebra. Some languages fix this by using a different symbol for assignment like `:` or `:=`. It doesn't help either when trying to explain the difference between `=` (assignment) and `==` (equality operator).

I'll add a few lines to help denote this better. Thanks for the feedback.

By the way the docs folder is the compiled html. If you want to reference the source code to the documentation you can see the raw markdown in the [pages folder](https://github.com/RVAGameJams/learn2love/tree/master/pages). This is compiled into the html using `yarn build` or `npm run build`: [package.json](https://github.com/RVAGameJams/learn2love/blob/be92e8ca4c72c004b8969ce697890b3ecaf8f2f9/package.json#L9-L10)

**Comment by JimmyStevens** [comment]
Yea, I figured from your work on webtrader you would use Yarn, so I already pulled it down and started working on it. But I have to start over because I didn't fork it. I will send a couple pull requests for some tricks that you may want to add to your book that I found really helpful.
