### ISSUE TITLE
[Chapter 3] Add section about primitives and referenced values

### ISSUE THREAD

**Issue by jaythomas** [RVAGameJams/learn2love#15]
This should discuss the difference between primitive data types (strings, numbers) and composite data types (tables) and how two variables can references the same data.

As with other sections, this section should include an exercise or two.

**Comment by ValentinChCloud** [comment]
Hello, I can help on it

**Comment by jaythomas** [comment]
@ValentinChCloud that would be great! If you are interested I will assign you the issue. If it helps you, this was something I stubbed weeks ago but please don't feel any obligation to use it:

> ```lua
> local string1 = "hello"
> local string2 = 'hello'
> 
> print(string1 == string2)
> 
> local number1 = 14
> local number2 = 14
> 
> print(number1 == number2)
> 
> local table1 = {}
> local table2 = {}
> 
> print(table1 == table2)
> 
> local function1 = function() end
> local function2 = function() end
> 
> print(function1 == function2)
> ```
> 
> What would happen if you were to run this?
> In chapter 1 we learned about comparing string with the `==` operator when we talked about [booleans](01-08-booleans.md).
> Let's [run the code in the repl](https://repl.it/languages/Lua) and try it out:
> 
> ```
> true
> true
> false
> false
> ```
> 
> The strings equal and the numbers equal, but why aren't the tables and functions equal since they are both empty?
