### ISSUE TITLE
Keywords that are not normal language

### ISSUE THREAD

**Issue by JimmyStevens** [RVAGameJams/learn2love#3]
The term 'invoke' introduced here: 
https://github.com/RVAGameJams/learn2love/blob/208e6ddc6558b17af4608740a1e380b56d6aab9a/docs/pages/01-07-making-functions.html#L580

Can throw beginners. Maybe add a "key terms" section where programmer-ease is introduced.

**Comment by jaythomas** [comment]
This term is introduced in an earlier section:
https://github.com/RVAGameJams/learn2love/blob/208e6ddc6558b17af4608740a1e380b56d6aab9a/docs/pages/01-04-using-functions.html#L560
and defined again in the end-of-chapter review: https://github.com/RVAGameJams/learn2love/blob/208e6ddc6558b17af4608740a1e380b56d6aab9a/docs/pages/01-18-chapter-review.html#L554

**Comment by JimmyStevens** [comment]
Ahhh, nevermid. Good to have.
