### ISSUE TITLE
CTRL-enter to run script in Repl.it on Windows?

### ISSUE THREAD

**Issue by einarpersson** [RVAGameJams/learn2love#35]
[Here](https://rvagamejams.com/learn2love/pages/01-06-scripting-and-printing.html) it says

> when using a text editor along-side the REPL you can run the code without the mouse by pressing 'command + enter' on Mac and **'Alt + enter'** on Windows. 

At least on my computer, this does not work. `CTRL-enter`  do work, however.
(might be a locale thing, since I'm using a Swedish keyboard with åäö).

This is in Chrome, running under Window 10 Pro.

**Comment by jaythomas** [comment]
Thanks for the info. Maybe it is a locale thing or the key bindings on the site have changed. I'll check from a Windows machine when I get a minute and update the instructions accordingly.
