### ISSUE TITLE
Lua REPL not working as described in 1.1 Interactive coding

### ISSUE THREAD

**Issue by elmimmo** [RVAGameJams/learn2love#37]
Chapter **1.1 Interactive coding** recommends the Lua REPL at https://repl.it/languages/Lua and then proceeds with:

> Type:
> 
>     2 + 2
>
> Then hit ENTER and immediately the REPL will Print out:
> 
>     =▸ 4

but what I get is:

    lua: [string "<eval>"]:1: unexpected symbol near '2'

**Comment by jaythomas** [comment]
Hi @elmimmo there are two window panes on repl.it's website and the right pane is actually the REPL that will evaluate your code on enter. Can you verify you typed it there and not in the left pane?

**Comment by elmimmo** [comment]
For whatever reason, input did not work in the right pane when I tried, so I assumed it was just for output. I tried again and it indeed works as you say.
