### ISSUE TITLE
REPL issue with comparing

### ISSUE THREAD

**Issue by JimmyStevens** [RVAGameJams/learn2love#4]
At https://rvagamejams.com/learn2love/pages/01-08-booleans.html

number = 5
number == 5

should return 'true'.

Instead REPL returns:

[string "number = 5..."]:5: '=' expected near '=='

**Comment by jaythomas** [comment]
Are you typing that into the repl or are you copying and pasting? If you copy and paste into the repl it won't recognize the newline between the two statement. When you paste it shows a `..`before the next line to signify that:

![repl](https://user-images.githubusercontent.com/2344456/44268938-06f22680-a201-11e8-875e-97cc2e3ffa60.png)

Pasting multiple lines only works in the text editor.

**Comment by JimmyStevens** [comment]
Typing

**Comment by jaythomas** [comment]
I can't replicate your issue. If you type it in, I'm assuming you're hitting enter between each statement. Here's my repl:
```
 > number = 5
 > number == 5
=> true
```

See the screenshot above: first I typed it and it returned true the I tried pasting it and got the error.

**Comment by JimmyStevens** [comment]
Issue exists when typing in editor, not REPL
