### ISSUE TITLE
Spelling, grammer, etc...

### ISSUE THREAD

**Issue by JimmyStevens** [RVAGameJams/learn2love#5]
I have seen a missing period and maybe one other error so far, but I wasn't gonna go through the effort of a pull request for that, so I will just add to the checklist below with a line to reference anytime I find more in the future. 

 

- [ ] 

This line reads funny, "It's basically like an if that skip when the first if passes..." 
https://github.com/RVAGameJams/learn2love/blob/dadf50fa661ba31a178c0c2ef8c66b2f6523ce7d/docs/pages/01-09-flow-control.html#L691

**Comment by JimmyStevens** [comment]
- [ ]

**Comment by jaythomas** [comment]
Sorry for the late reply. If you spot any typos feel free to put in a pull request even if it's small. I'll go ahead and get that one since you pointed it out.
