### ISSUE TITLE
Road blocks into chapter 2

### ISSUE THREAD

**Issue by JimmyStevens** [RVAGameJams/learn2love#8]
This intro section I can complete, but knowing where a green developer attempting to learn without a mentor may be.... they would be completely blocked here. 

I could take while to explain all the challenges, but it may be necessary to explain to the user they need a mentor to get them up and running in section 2.1. Or, it may be worth breaking out a whole section on items such as:

- what exactly is a text editor (seems benign, but this is confusing). 
- what is the difference between OS systems and getting the app to run
- how to read the LOVE app documentation to get the app running on different OS systems (very daunting to new developers)
- what is a terminal / CLI
- what are pathways `this/is/a/pathway/to/a/directory and this/is/a/pathway/to/a/directory/file.file`
- what is a directory vs folder (no difference, but causes confusion to noobs). 

Remember we just went from a cozy place on a website that had a REPL and lua text editor so you could see code work to all the these new tools and background knowledge that is necessary on your machine to run LOVE. This is one of the proverbial cliffs that many beginners face every time they try to go from class to practice.

**Comment by jaythomas** [comment]
My original intent was to offer guidance without giving an opinion on what tools to use (popular text editors come and go, for instance), but it's a double-edged sword as many users aren't going to be technically inclined to where they even know what to type in a search engine to find one. It's a section I want to re-visit after I finish the current (rather large) section I am on. I'll leave this issue open until then. I don't have OSX so any stepping stones you can think of that would help those users is super welcome.

**Comment by rm-code** [comment]
I opened a PR which changes the IDE section a bit. I linked to the awesome-love2d IDE section which lists a bunch of text editors and IDEs commonly used for LÖVE development.

It is a community effort so I assume it would be always up to date.

**Comment by rm-code** [comment]
We should probably also include a section about what we mean by ".love" file (unless it already exists somewhere and I just missed it).

**Comment by jaythomas** [comment]
I was thinking of finishing the chapter with a section on distributing and running other people's love games. Unfortunately I haven't gotten quite that far.

**Comment by jaythomas** [comment]
Changes now published.
